### ISSUE TITLE
Projects 01, 02, 03 have a runtime warning

### ISSUE THREAD

**Issue by ScrappyCocco** [ScrappyCocco/DirectX-DXR-Tutorials#1]
Project 3 (Per Instance Data) throws the following warnign at runtime:
```
D3D12 ERROR: ID3D12CommandList::DispatchRays: pDesc->HitGroupTable.StartAddress must be aligned to 64 bytes (D3D12_RAYTRACING_SHADER_TABLE_BYTE_ALIGNMENT) and .StrideInBytes must be aligned to 32 bytes (D3D12_RAYTRACING_SHADER_RECORD_BYTE_ALIGNMENT). [ EXECUTION ERROR #1161: DISPATCH_RAYS_INVALID]

```

**Comment by ScrappyCocco** [comment]
Update: The same error appear in tutorial 01 and 02 when using the DXR pipeline instead of the rasterizer

That error tho doesn't appear in tutorial 04 and 05, maybe with the introduction of shadows(?)

**Comment by ScrappyCocco** [comment]
The problem is most likely in this section here, that has broken sizes: [D3D12HelloTriangle.cpp#L396](https://github.com/ScrappyCocco/DirectX-DXR-Tutorials/blob/master/01-Dx12DXRTriangle/Project/D3D12HelloTriangle.cpp#L396)

But fixing the alignment there doesn't work, as the shader table probably is mis-aligned too

![image](https://user-images.githubusercontent.com/11294898/95094279-05aa4d80-072a-11eb-8665-da14ab021c8e.png)

**Comment by siliconvoodoo** [comment]
it's not a warning, it's an error. and it's not fixed by adding padding as such
```
struct HitInfo {
  float4 colorAndDistance;
  float4 padding__;
};
```

**Comment by siliconvoodoo** [comment]
adding a table for the miss shader fixed it. I put a dummy float4 as CBV. it's a pain because it requires a full fledged desc heap.
weird choice from DX spec this alignment that can't be obtained with simplistic shaders.

**Comment by ScrappyCocco** [comment]
> adding a table for the miss shader fixed it. I put a dummy float4 as CBV. it's a pain because it requires a full fledged desc heap.
> weird choice from DX spec this alignment that can't be obtained with simplistic shaders.

This is good to know, but is not important anymore...(?)
As you can see from the log, the issue has been fixed and closed with a commit, that problem is no longer present in my code
